[package]
name = "shifty-dioxus"
version = "0.1.0"
authors = ["Simon Goller <neosam+github@posteo.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { version = "0.5", features = ["web", "router"] }

# Debug
tracing = "0.1.40"
dioxus-logger = "0.5.0"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.203", features = ["rc"] }
serde_json = "1.0.117"
async-recursion = "1.1.1"
futures = "0.3.30"
web-sys = "0.3.69"
thiserror = "1.0.61"
time = "0.3.36"

[dependencies.rest-types]
path = "../shifty-backend/rest-types"
[dependencies.uuid]
version = "*"
features = ["v4", "js"]
