[application]

# App (Project) Name
name = "shifty-dioxus"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "shifty-dioxus"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["/tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[[web.proxy]]
backend = "http://localhost:3000/slot"
[[web.proxy]]
backend = "http://localhost:3000/auth-info"
[[web.proxy]]
backend = "http://localhost:3000/booking"
[[web.proxy]]
backend = "http://localhost:3000/sales-person"
