// tokens.jsx — three aesthetic directions for Shifty design system
// Each direction defines: colors (light + dark), type, radii, density.

const DIRECTIONS = {
  kontor: {
    id: 'kontor',
    name: 'Kontor',
    tagline: 'Clean, professional, calm',
    description:
      'Linear/Notion-DNA. Cool neutrals, an indigo accent. Built for managers who live in this app all day. Low visual noise, generous structure.',
    fonts: {
      sans: '"Inter", "Helvetica Neue", system-ui, -apple-system, sans-serif',
      mono: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
      display:
        '"Inter", "Helvetica Neue", system-ui, -apple-system, sans-serif',
    },
    light: {
      bg: '#fbfbfc',
      surface: '#ffffff',
      surfaceAlt: '#f4f5f7',
      border: '#e6e8ec',
      borderStrong: '#d0d3da',
      ink: '#0e1117',
      inkSoft: '#3a4150',
      inkMuted: '#6b7382',
      accent: '#3a4cd1',
      accentInk: '#ffffff',
      accentSoft: '#eaecfb',
      good: '#0e7a4d',
      goodSoft: '#defaee',
      warn: '#a65a08',
      warnSoft: '#fef0d6',
      bad: '#b8281a',
      badSoft: '#fde4e1',
      // shift slot fills (low chroma)
      slotA: '#e7eaff',
      slotB: '#e6f4ec',
      slotC: '#fff0d6',
      slotD: '#fadfdb',
      slotE: '#eee6f8',
      slotF: '#dff1f3',
    },
    dark: {
      bg: '#0c0e13',
      surface: '#13161d',
      surfaceAlt: '#181c25',
      border: '#252a36',
      borderStrong: '#363c4b',
      ink: '#f3f4f7',
      inkSoft: '#c2c7d2',
      inkMuted: '#7d8493',
      accent: '#7c8cf5',
      accentInk: '#0c0e13',
      accentSoft: '#1c2348',
      good: '#4ad691',
      goodSoft: '#0e2a1d',
      warn: '#f3b15c',
      warnSoft: '#34250d',
      bad: '#ee6e62',
      badSoft: '#3a1814',
      slotA: '#1f2547',
      slotB: '#173024',
      slotC: '#3a2c12',
      slotD: '#3b1f1c',
      slotE: '#2a1f3c',
      slotF: '#143036',
    },
    radius: { sm: '4px', md: '6px', lg: '10px', xl: '14px' },
    shadow: '0 1px 2px rgba(15,18,30,0.06), 0 1px 0 rgba(15,18,30,0.04)',
    weight: { regular: 400, medium: 500, semibold: 600, bold: 700 },
    typeScale: {
      display: { size: '32px', line: '38px', weight: 700, tracking: '-0.02em' },
      h1: { size: '24px', line: '30px', weight: 600, tracking: '-0.01em' },
      h2: { size: '18px', line: '24px', weight: 600, tracking: '-0.005em' },
      body: { size: '14px', line: '20px', weight: 400, tracking: '0' },
      small: { size: '12px', line: '16px', weight: 500, tracking: '0' },
      micro: { size: '11px', line: '14px', weight: 600, tracking: '0.04em' },
    },
  },

  tagblatt: {
    id: 'tagblatt',
    name: 'Tagblatt',
    tagline: 'Editorial, warm, human',
    description:
      'Like a well-set printed schedule. Serif headlines, sandy off-whites, a terracotta accent. Less intimidating for staff — your team won\'t feel like they\'re inside an ERP.',
    fonts: {
      sans: '"Söhne", "Inter", "Helvetica Neue", system-ui, sans-serif',
      mono: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
      display:
        '"Source Serif 4", "Source Serif Pro", "Charter", Georgia, serif',
    },
    light: {
      bg: '#f6f1e8',
      surface: '#fcf8f1',
      surfaceAlt: '#efe8da',
      border: '#e2d8c4',
      borderStrong: '#cdc0a4',
      ink: '#23201a',
      inkSoft: '#4a443a',
      inkMuted: '#7d7565',
      accent: '#b34a2a',
      accentInk: '#fcf8f1',
      accentSoft: '#f4dccf',
      good: '#3e6b3a',
      goodSoft: '#dfe9d4',
      warn: '#9c6e10',
      warnSoft: '#f3e2b6',
      bad: '#9b2a1a',
      badSoft: '#eccfc8',
      slotA: '#f1e3d2',
      slotB: '#e2ecd6',
      slotC: '#f3e2b6',
      slotD: '#eccfc8',
      slotE: '#e3dcef',
      slotF: '#d8e7e8',
    },
    dark: {
      bg: '#1a1611',
      surface: '#221d16',
      surfaceAlt: '#2c251c',
      border: '#3a3225',
      borderStrong: '#544835',
      ink: '#f3ecde',
      inkSoft: '#d8cfbd',
      inkMuted: '#9e9277',
      accent: '#e07a55',
      accentInk: '#1a1611',
      accentSoft: '#3a2017',
      good: '#9bc585',
      goodSoft: '#1f2c19',
      warn: '#e8c265',
      warnSoft: '#2e2511',
      bad: '#e88476',
      badSoft: '#321810',
      slotA: '#3a2a1c',
      slotB: '#1f2c19',
      slotC: '#332811',
      slotD: '#321a14',
      slotE: '#2a2335',
      slotF: '#15292c',
    },
    radius: { sm: '2px', md: '4px', lg: '6px', xl: '8px' },
    shadow: '0 1px 2px rgba(80,55,30,0.08), 0 1px 0 rgba(80,55,30,0.04)',
    weight: { regular: 400, medium: 500, semibold: 600, bold: 700 },
    typeScale: {
      display: { size: '38px', line: '42px', weight: 600, tracking: '-0.015em', family: 'display' },
      h1: { size: '26px', line: '32px', weight: 600, tracking: '-0.01em', family: 'display' },
      h2: { size: '18px', line: '24px', weight: 500, tracking: '0', family: 'display' },
      body: { size: '15px', line: '22px', weight: 400, tracking: '0' },
      small: { size: '13px', line: '18px', weight: 500, tracking: '0' },
      micro: { size: '11px', line: '14px', weight: 600, tracking: '0.06em' },
    },
  },

  plotter: {
    id: 'plotter',
    name: 'Plotter',
    tagline: 'Dense, monospaced, power-user',
    description:
      'Information per pixel. Mono numerics, hairline rules, two saturated alarm colors. For dispatchers who need to see twelve people across seven days without scrolling.',
    fonts: {
      sans: '"IBM Plex Sans", "Inter", system-ui, sans-serif',
      mono: '"IBM Plex Mono", "JetBrains Mono", ui-monospace, Menlo, monospace',
      display:
        '"IBM Plex Mono", "JetBrains Mono", ui-monospace, Menlo, monospace',
    },
    light: {
      bg: '#fafaf7',
      surface: '#ffffff',
      surfaceAlt: '#f1f1ec',
      border: '#d8d8d0',
      borderStrong: '#9c9c92',
      ink: '#0a0a08',
      inkSoft: '#2c2c28',
      inkMuted: '#686864',
      accent: '#0a6e6e',
      accentInk: '#ffffff',
      accentSoft: '#cfeaea',
      good: '#0a6e34',
      goodSoft: '#cfead8',
      warn: '#9b5b00',
      warnSoft: '#f5dcb0',
      bad: '#b81c1c',
      badSoft: '#f5cece',
      slotA: '#e6efef',
      slotB: '#e3eedb',
      slotC: '#f5dcb0',
      slotD: '#f5cece',
      slotE: '#e3dded',
      slotF: '#d8e9eb',
    },
    dark: {
      bg: '#0a0b08',
      surface: '#101108',
      surfaceAlt: '#161812',
      border: '#262922',
      borderStrong: '#3d4138',
      ink: '#e8ecdc',
      inkSoft: '#c0c4b4',
      inkMuted: '#787c70',
      accent: '#5cdcd0',
      accentInk: '#0a0b08',
      accentSoft: '#0e2c2a',
      good: '#7fdc7f',
      goodSoft: '#0f2614',
      warn: '#f0c259',
      warnSoft: '#2c200a',
      bad: '#f06a6a',
      badSoft: '#2a1010',
      slotA: '#152323',
      slotB: '#1a2614',
      slotC: '#2a2010',
      slotD: '#2a1414',
      slotE: '#1f1a2c',
      slotF: '#0e2528',
    },
    radius: { sm: '0px', md: '2px', lg: '2px', xl: '4px' },
    shadow: 'none',
    weight: { regular: 400, medium: 500, semibold: 600, bold: 700 },
    typeScale: {
      display: { size: '28px', line: '32px', weight: 600, tracking: '-0.01em', family: 'mono' },
      h1: { size: '20px', line: '26px', weight: 600, tracking: '0', family: 'mono' },
      h2: { size: '14px', line: '20px', weight: 600, tracking: '0.04em' },
      body: { size: '13px', line: '20px', weight: 400, tracking: '0' },
      small: { size: '12px', line: '16px', weight: 500, tracking: '0.02em' },
      micro: { size: '10px', line: '14px', weight: 700, tracking: '0.08em' },
    },
  },
};

window.SHIFTY_DIRECTIONS = DIRECTIONS;
