name: Release

on:
  push:
    tags:
     - 'v*.*.*'

env:
  add_binaries_to_github_release: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: olegtarasov/get-tag@v2.1.2
      id: get_version
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Cache Dioxus CLI
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/dx
        key: ${{ runner.os }}-dioxus-v0.6.5
        restore-keys: |
          ${{ runner.os }}-dioxus-v0.6.5
    - name: Install dioxus
      run: |
        if which dx > /dev/null; then
          echo "dioxus is already installed"
        else
          cargo install dioxus-cli
        fi
    - name: Install tailwindcss
      run: npm install tailwindcss
    # - name: Formatting
    #   run: cargo fmt --all -- --check
    - name: Run tailwindcss
      run: npx tailwindcss -i ./input.css -o assets/tailwind.css
    - name: Build release 
      run: dx build --release
    - name: Package dist as dist.tgz
      run: tar -czf dist.tgz dist/
    - name: Upload dist directory as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist.tgz
        path: dist.tgz
        retention-days: 1
    - name: Upload binaries to release
      if: ${{ env.add_binaries_to_github_release == 'true' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist.tgz
        asset_name: shifty-frontend-${{ steps.get_version.outputs.tag }}.tgz
        tag: ${{ github.ref }}
        overwrite: true