name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: "true"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dioxus
      run: cargo install dioxus-cli
    # - name: Formatting
    #   run: cargo fmt --all -- --check
    - name: Build local version
      run: dx build
